### ISSUE TITLE
Game doesn't start :/

### ISSUE THREAD

**Issue by gustlik** [ElmoDFGD/ElmoRim#12]
Hi,
After clear install according to instruction. Game doesn't work. I reinstalled everything starting from base game to be sure, but nothing has chnaged. Screenshots below. Could you suggest how to fix it? Thank you.
![SkyrimSE 2023-02-10 16-38-15](https://user-images.githubusercontent.com/689938/218132869-a470265e-dc3f-494e-b9d5-fae9dff1f7d8.png)
![SkyrimSE 2023-02-10 16-38-22](https://user-images.githubusercontent.com/689938/218132896-1ccc1b39-a663-4585-9dca-1e0dc6489d26.png)
![SkyrimSE 2023-02-10 16-38-24](https://user-images.githubusercontent.com/689938/218132904-d9f1a3f2-4672-4e59-87d8-0dd2904ac38f.png)
![SkyrimSE 2023-02-10 16-38-28](https://user-images.githubusercontent.com/689938/218132915-210afe5d-bf20-426d-9a2e-18563dea30b2.png)

**Comment by ElmoDFGD** [comment]
Use the SKSE-executable to launch the game instead. For future reference, these questions are best asked in the #support channel on the discord - the issue tracker is to track known bugs and is not regularly monitored.

**Comment by gustlik** [comment]
I tried it, but it didn't help. With skse it doesn't run at all.

**Comment by ElmoDFGD** [comment]
Alright, check in on the discord where I have suggested a few solutions.

**Comment by gustlik** [comment]
I moved to different modlist. I already lost few earlier days on debugging your list. If you are between 30-40 years old and have few kids (and less time for games and hobbies), its normal that you would like to have a list that works out of the box.
