### ISSUE TITLE
Animation snap during sprint normal attack

### ISSUE THREAD

**Issue by fiorezy** [ElmoDFGD/ElmoRim#13]
There is a noticeable animation snap while normal attacking during sprint, occurs only with some weapons.
Tested with war axes, battleaxes, war hammers,

How to reproduce:
1. Equip a war axe, battleaxe, or a war hammer
2. Sprint then use a light attack

https://user-images.githubusercontent.com/125289478/218501294-668484b0-f03f-423a-82ab-a4a742009796.mp4

**Comment by ElmoDFGD** [comment]
130223 - Recreated w/ only MCO installed aka MCO issue. Wait for MCO update or add moveset w/ MCO_sprint.hkx behavior file.

**Comment by ElmoDFGD** [comment]
Fixed in 1.0.0RC2

**Comment by fiorezy** [comment]
It's still there

**Comment by ElmoDFGD** [comment]
Could you provide a new video? In my testing the new animations look fine. Thanks!

**Comment by ElmoDFGD** [comment]
Issue reopened.
Axes/Maces still problematic. Warhammers/Battleaxes work well w/ new animation.
Awaiting MCO update.

**Comment by fiorezy** [comment]
[Fix Forward Attack Snap.zip](https://github.com/ElmoDFGD/ElmoRim/files/10761354/Fix.Forward.Attack.Snap.zip)
I made this fix as a workaround, it should eliminate all the snap attacks including dual wield
Note that I used a tweaked esp from Eskyrim Sprint Attacks For MCO/Skysa, but I was unable to replace the sprint power attack animation with the esp enabled

**Comment by ElmoDFGD** [comment]
Workaround incorporated into ElmoRim. Leaving issue open until MCO gets updated.

**Comment by ElmoDFGD** [comment]
fixed in 2.0
