### ISSUE TITLE
Clipping with scale armor

### ISSUE THREAD

**Issue by fiorezy** [ElmoDFGD/ElmoRim#14]
![image](https://user-images.githubusercontent.com/125289478/218502942-05904648-aced-4f86-97cb-c868b29a076d.png)

**Comment by ElmoDFGD** [comment]
130223 Wrote to mod authors of Nordic MCO + Modular armory. Checking TPF discord for input.

**Comment by ElmoDFGD** [comment]
160223 Feedback from TPF discord: Hard to fix without physics enabled skirt-part.
H#1 Compare w/ vanilla behavior, brute force enabling of mods to rule out animations.
H#2 Mitigate by using different idle animation.
H#3 Find physics enabled model replacer.

**Comment by ElmoDFGD** [comment]
H#2 + thiccened skirt part of the mesh should mitigate the worst of the clipping. Not perfect but will have to do.
![image](https://user-images.githubusercontent.com/118224262/219484745-b189a050-c6bb-479b-b3f8-81ed264ea81c.png)
