### ISSUE TITLE
Interrupted NPC dialogues

### ISSUE THREAD

**Issue by ribeirojc1** [ElmoDFGD/ElmoRim#15]
Upon entering Winterhold's inn, there's the conversation between Nelacar and Dagur.
But they do not complete the dialogue and I can't interact with either of them.

Similar problem when entering the Riverwood trader, Lucan and Camila don't complete their conversation.
But I can talk to them normally, unlike what happens in Winterhold.

**Comment by ElmoDFGD** [comment]
Cause: Pause After Load Unscripted NG
H#1: Tweak length of pause
H#2: Remove mod

**Comment by ElmoDFGD** [comment]
H#1 OK. ResumeAfter=2.0. 
Leaving issue open while waiting for input from author of Skyrim Upscaler.

**Comment by ElmoDFGD** [comment]
Closing issue. Fixed and separate upscaler questions is tracked in issue #19
