### ISSUE TITLE
Draw 2

### ISSUE THREAD

**Issue by fiorezy** [ElmoDFGD/ElmoRim#16]
Correct animation doesn't play with a shield equipped

**Comment by ElmoDFGD** [comment]
Please specify which combination of Left/Right hand gear + screenshot of settings

**Comment by fiorezy** [comment]
https://user-images.githubusercontent.com/125289478/220348238-761f79d8-06e0-4abc-ac63-9ac62a1c3781.mp4

**Comment by ElmoDFGD** [comment]
Thank you! Will be fixed in the next patch.

**Comment by ElmoDFGD** [comment]
Fixed in 1.1.0
