### ISSUE TITLE
CTD when equipping Savior's Hide (only female characters)

### ISSUE THREAD

**Issue by aqvbens** [ElmoDFGD/ElmoRim#17]
Get a CTD when equipping the unique armor Savior's Hide.
It seems to happen ONLY if you select a FEMALE character! (I tried with 2 males and it just worked as intended)
It doesn't matter what color of Savior's Hide armor you equip (there are 3 colors of the same armor in game)
you always get that CTD.

I saw that Savior's Hide gets modified by Reliquary of Myth mod, so I tried to equip another armor that gets
modified by this mod which was "The Ebony Mail" and I got no crashes.
I think that this issue happens only with Savior's Hide but Im not entirely sure though as I didnt try all the
other gear touched by this mod.

_**How to recreate:**
New save file, chose female sex type and then "player.additem [IDs: 0002ac61, fe09ed63, fe09eb68] 1"
and then equip it to get CTD._

**Comment by ElmoDFGD** [comment]
Fixed in 1.1.1
