### ISSUE TITLE
Unable to feed on certain npc's

### ISSUE THREAD

**Issue by nolanisme2** [ElmoDFGD/ElmoRim#18]
After completing the taste of death quest and putting the ring of namira on, I have been unable to feed on most corpses. So far the only success I've had is with a forsworn brairheart and the man in the quest. However I have only ran into vampires and forsworn (I'm in the reach) 

Here was what I was seeing when interacting with corpses, I've tried crouching, both first and third person, m&kb and controller

![SkyrimSE_c77i5y3N1Q](https://user-images.githubusercontent.com/10508876/227016469-5d985a55-d07c-4c07-bb70-a047a32b9306.png)

This is my Sunhelm MCM

![SkyrimSE_CK7IKyCyxN](https://user-images.githubusercontent.com/10508876/227016771-64d3c762-f72b-4ebe-bce6-710ad588a467.png)

**Comment by ElmoDFGD** [comment]
On the same topic from Rusty Replicant:
Found a bug with Namira's Blessing cannibal perk. It's supposed to give 10 health per feeding for 5 minutes,and stack up to 10 times, but it actually gives 100 health per feeding and seems to stack as many times as you can feed. I've gone from 180ish health all the way up to 1480ish health. That would be 13 stacks at 100 per stack. Kinda makes you invincible as long as you can keep eating people.

**Comment by ElmoDFGD** [comment]
Conflict between Sunhelm and RoM. Fixed in 1.2.0 by switching to TFN.
