### ISSUE TITLE
Screen Freeze Bug

### ISSUE THREAD

**Issue by Nosnafein** [ElmoDFGD/ElmoRim#19]
Experiencing a bug where my screen will kind of freeze, but the game is still running and i can move around, my screen gets distorted whenever anything moves, but when everything is still it goes back to the frame it got stuck on. This happens whenever my temperature changes through Sunhelm, or if I disable the mod or the cold weather visual effect through the MCM. It persists through loading/restarting the game, but I can get rid of it by loading a save before it happens.

I fixed it by disabling Sunhelm's cold weather visual effect, then restarting my game.

**Comment by ElmoDFGD** [comment]
Issue reported to PureDark. Awaiting update of Skyrim Upscaler

**Comment by ElmoDFGD** [comment]
Fixed in 1.3.0RC1 by removing the upscaler.
