### ISSUE TITLE
Rueful Axe Frenzy

### ISSUE THREAD

**Issue by Nosnafein** [ElmoDFGD/ElmoRim#21]
This is not really a bug, so much as the AI for the player when the effect triggers is really bad.
Your character ignores any enemies attacking them, and picks a target that they will try to kill. It takes a while to pick a target after the effect triggers or if you manage to kill your target, and during that time you will move randomly or stand still with the axe sheathed, most of the time you just die the moment the effect triggers because you ignore the enemies attacking you. Once you do find a target you try to pathfind towards them, often failing and just standing there looking at the target. If you run out of possible targets, you will just stand there until the effect ends.

This effect is from Reliquary of Myth, the nexus page has a console command for disabling the frenzy effect. 

"Set ROM_DA03_RandomAttackToggle_Global to 0"

With the command enabled you still get the visual effect, which is nice, but you can control you character as normal and don't have to deal with the buggy part of the effect. It says that NPC's should still be frenzied but they aren't.

**Comment by ElmoDFGD** [comment]
Will probably swap out RoM for Vestige.

**Comment by ElmoDFGD** [comment]
Fixed in 1.3.0RC1 by switching to Antiquary.
