### ISSUE TITLE
Graphical issues with blowing snow effect

### ISSUE THREAD

**Issue by jtrippin** [ElmoDFGD/ElmoRim#9]
This is on ElmoRim 0.1.2, so apologies if the ENB changes in 0.1.4 already fixed this.

The blowing snow effect is boxy and discolored. I tested it outside of High Hrothgar where it is easy to see against the edge of the mountain. 

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 12 30 - 23 26 33 81](https://user-images.githubusercontent.com/74123655/210126313-6cf7a16e-e5e3-410a-917c-02b34d5ced7d.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 12 30 - 23 26 44 86](https://user-images.githubusercontent.com/74123655/210126314-ed87e8ea-9a21-46e7-a257-c96d21f12f68.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 12 30 - 23 26 53 36](https://user-images.githubusercontent.com/74123655/210126316-a85ed5bb-119f-474e-980b-a1fdf1c2fbfd.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 12 30 - 23 25 26 57](https://user-images.githubusercontent.com/74123655/210126317-80345d10-3b47-44bb-8230-8db08e311f61.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 12 30 - 23 25 33 62](https://user-images.githubusercontent.com/74123655/210126321-76663ada-2479-4558-9310-856c24d6fbc0.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 12 30 - 23 25 34 71](https://user-images.githubusercontent.com/74123655/210126324-1630db74-539a-459d-ae2e-a2ef1131b6e4.png)

**Comment by ElmoDFGD** [comment]
Fixed in 0.1.5.
